# Generated by Django 6.0.3 on 2026-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_rows',
            field=models.PositiveIntegerField(blank=True, help_text='(Regular) Number of rows in the classroom.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='num_systems',
            field=models.PositiveIntegerField(blank=True, help_text='(Lab) Total number of computer systems.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('regular', 'Regular Class'), ('lab', 'Lab'), ('conference', 'Executive Conference Room')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='seats_per_batch',
            field=models.PositiveIntegerField(blank=True, help_text='(Lab) Students accommodated per batch.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='seats_per_table',
            field=models.PositiveIntegerField(blank=True, help_text='(Regular) Seating capacity per table.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='tables_per_row',
            field=models.PositiveIntegerField(blank=True, help_text='(Regular) Tables per row.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='total_seats',
            field=models.PositiveIntegerField(blank=True, help_text='(Conference) Total seats (= systems).', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
